package conversations

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/skzv/ccmux/internal/agent"
)

// slashCommandSession is a real-shaped Claude transcript that opens
// with /model (caveat isMeta event, command record, stdout record), then
// a pasted-image prompt with its isMeta image note, then /plan with a
// prompt, then a compaction summary.
const slashCommandSession = `{"type":"user","isMeta":true,"cwd":"/p","entrypoint":"cli","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"},"timestamp":"2026-04-30T10:00:00Z"}
{"type":"user","cwd":"/p","message":{"role":"user","content":"<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>fable</command-args>"},"timestamp":"2026-04-30T10:00:01Z"}
{"type":"user","cwd":"/p","message":{"role":"user","content":"<local-command-stdout>Set model to Fable 5 and saved as your default</local-command-stdout>"},"timestamp":"2026-04-30T10:00:02Z"}
{"type":"user","cwd":"/p","message":{"role":"user","content":[{"type":"text","text":"why is the build red?"}]},"timestamp":"2026-04-30T10:00:03Z"}
{"type":"user","isMeta":true,"cwd":"/p","message":{"role":"user","content":[{"type":"text","text":"[Image: source: /tmp/shot.png]"}]},"timestamp":"2026-04-30T10:00:04Z"}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"A missing import."}]},"timestamp":"2026-04-30T10:00:05Z"}
{"type":"user","cwd":"/p","message":{"role":"user","content":"<command-name>/plan</command-name>\n            <command-message>plan</command-message>\n            <command-args>add a scroller view</command-args>"},"timestamp":"2026-04-30T10:00:06Z"}
{"type":"user","cwd":"/p","message":{"role":"user","content":"<local-command-stdout>Enabled plan mode</local-command-stdout>"},"timestamp":"2026-04-30T10:00:07Z"}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Here is the plan."}]},"timestamp":"2026-04-30T10:00:08Z"}
{"type":"user","isCompactSummary":true,"isVisibleInTranscriptOnly":true,"cwd":"/p","message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context."},"timestamp":"2026-04-30T10:00:09Z"}
`

// TestListClaude_PreviewSkipsSlashCommandCaveat — regression: a session
// that started with /model showed "Caveat: The messages below were
// generated by the user while running local commands…" as its preview.
func TestListClaude_PreviewSkipsSlashCommandCaveat(t *testing.T) {
	home := t.TempDir()
	writeFile(t, filepath.Join(home, ".claude/projects/-p/sess-1.jsonl"), slashCommandSession)
	got, err := ListClaude(home)
	if err != nil || len(got) != 1 {
		t.Fatalf("ListClaude = %v, %v", got, err)
	}
	if got[0].Preview != "why is the build red?" {
		t.Errorf("Preview = %q, want the first typed prompt", got[0].Preview)
	}
}

// TestRecentMessages_ClaudeSkipsMetaAndCommandRecords — regression: the
// transcript modal listed the caveat, the /model command record and
// its stdout as user turns (and the counter counted them).
func TestRecentMessages_ClaudeSkipsMetaAndCommandRecords(t *testing.T) {
	path := filepath.Join(t.TempDir(), "sess-1.jsonl")
	writeFile(t, path, slashCommandSession)
	c := Conversation{Agent: agent.IDClaude, Path: path}

	msgs, err := RecentMessages(c, 50)
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for _, m := range msgs {
		got = append(got, m.Role+": "+m.Content)
	}
	want := []string{
		"user: why is the build red?",
		"assistant: A missing import.",
		"user: add a scroller view",
		"assistant: Here is the plan.",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("RecentMessages =\n%s\nwant\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	if n, err := CountMessages(c); err != nil || n != len(want) {
		t.Errorf("CountMessages = %d, %v; want %d", n, err, len(want))
	}
}

func TestCleanPromptText_DropsSlashCommandBlocks(t *testing.T) {
	cases := []struct{ in, want string }{
		{"<local-command-caveat>Caveat: generated by local commands.</local-command-caveat>", ""},
		{"<command-name>/model</command-name>\n  <command-message>model</command-message>\n  <command-args></command-args>", ""},
		{"<command-name>/model</command-name>\n  <command-message>model</command-message>\n  <command-args>fable</command-args>", ""},
		{"<command-name>/plan</command-name>\n  <command-message>plan</command-message>\n  <command-args>build the thing</command-args>", "build the thing"},
		{"<command-message>review is running…</command-message>\n<command-name>/review</command-name>\n<command-args>check the auth flow</command-args>", "check the auth flow"},
		{"<local-command-stdout>Set model to Fable</local-command-stdout>", ""},
		{"<local-command-stderr>boom</local-command-stderr>", ""},
		{"<local-command-stdout>unterminated", "unterminated"},
	}
	for _, tc := range cases {
		if got := strings.Join(strings.Fields(cleanPromptText(tc.in)), " "); got != tc.want {
			t.Errorf("cleanPromptText(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}
